### ISSUE TITLE
Morning session: peer-to-peer code review 09/03/2021

### ISSUE THREAD

**Issue by Felipeg005** [ad9311/leaderboard-api#4]
Hi Angel, thank you for sharing your code, It's very clean and the output has a great design!!, very nice work! :+1:

**Comment by DanSam5K** [comment]
- A very impressive implementation and demonstration of hard work keep it up 👍 .

**Comment by Hamzaoutdoors** [comment]
## Hi Angel,

:+1: The app is properly styled and its layout looks like the wireframe. Adding a message is awesome. :clap: :clap: 
:+1: README file looks professional.

Well done, Your project is complete!
